# Generated by Django 4.0.3 on 2022-03-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivePic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter', models.CharField(max_length=10)),
            ],
        ),
    ]
